# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mlkeller/cpe473/part5

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mlkeller/cpe473/part5/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mlkeller/cpe473/part5/build/CMakeFiles /home/mlkeller/cpe473/part5/build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mlkeller/cpe473/part5/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named parser

# Build rule for target.
parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 parser
.PHONY : parser

# fast build rule for target.
parser/fast:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/build
.PHONY : parser/fast

#=============================================================================
# Target rules for targets named raytrace

# Build rule for target.
raytrace: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 raytrace
.PHONY : raytrace

# fast build rule for target.
raytrace/fast:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/build
.PHONY : raytrace/fast

lib/parser/Parser.o: lib/parser/Parser.cpp.o
.PHONY : lib/parser/Parser.o

# target to build an object file
lib/parser/Parser.cpp.o:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/lib/parser/Parser.cpp.o
.PHONY : lib/parser/Parser.cpp.o

lib/parser/Parser.i: lib/parser/Parser.cpp.i
.PHONY : lib/parser/Parser.i

# target to preprocess a source file
lib/parser/Parser.cpp.i:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/lib/parser/Parser.cpp.i
.PHONY : lib/parser/Parser.cpp.i

lib/parser/Parser.s: lib/parser/Parser.cpp.s
.PHONY : lib/parser/Parser.s

# target to generate assembly for a file
lib/parser/Parser.cpp.s:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/lib/parser/Parser.cpp.s
.PHONY : lib/parser/Parser.cpp.s

lib/parser/TokenStream.o: lib/parser/TokenStream.cpp.o
.PHONY : lib/parser/TokenStream.o

# target to build an object file
lib/parser/TokenStream.cpp.o:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/lib/parser/TokenStream.cpp.o
.PHONY : lib/parser/TokenStream.cpp.o

lib/parser/TokenStream.i: lib/parser/TokenStream.cpp.i
.PHONY : lib/parser/TokenStream.i

# target to preprocess a source file
lib/parser/TokenStream.cpp.i:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/lib/parser/TokenStream.cpp.i
.PHONY : lib/parser/TokenStream.cpp.i

lib/parser/TokenStream.s: lib/parser/TokenStream.cpp.s
.PHONY : lib/parser/TokenStream.s

# target to generate assembly for a file
lib/parser/TokenStream.cpp.s:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/lib/parser/TokenStream.cpp.s
.PHONY : lib/parser/TokenStream.cpp.s

lib/parser/Tokenizer.o: lib/parser/Tokenizer.cpp.o
.PHONY : lib/parser/Tokenizer.o

# target to build an object file
lib/parser/Tokenizer.cpp.o:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/lib/parser/Tokenizer.cpp.o
.PHONY : lib/parser/Tokenizer.cpp.o

lib/parser/Tokenizer.i: lib/parser/Tokenizer.cpp.i
.PHONY : lib/parser/Tokenizer.i

# target to preprocess a source file
lib/parser/Tokenizer.cpp.i:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/lib/parser/Tokenizer.cpp.i
.PHONY : lib/parser/Tokenizer.cpp.i

lib/parser/Tokenizer.s: lib/parser/Tokenizer.cpp.s
.PHONY : lib/parser/Tokenizer.s

# target to generate assembly for a file
lib/parser/Tokenizer.cpp.s:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/lib/parser/Tokenizer.cpp.s
.PHONY : lib/parser/Tokenizer.cpp.s

src/Application/Application.o: src/Application/Application.cpp.o
.PHONY : src/Application/Application.o

# target to build an object file
src/Application/Application.cpp.o:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Application/Application.cpp.o
.PHONY : src/Application/Application.cpp.o

src/Application/Application.i: src/Application/Application.cpp.i
.PHONY : src/Application/Application.i

# target to preprocess a source file
src/Application/Application.cpp.i:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Application/Application.cpp.i
.PHONY : src/Application/Application.cpp.i

src/Application/Application.s: src/Application/Application.cpp.s
.PHONY : src/Application/Application.s

# target to generate assembly for a file
src/Application/Application.cpp.s:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Application/Application.cpp.s
.PHONY : src/Application/Application.cpp.s

src/Application/RayInfo.o: src/Application/RayInfo.cpp.o
.PHONY : src/Application/RayInfo.o

# target to build an object file
src/Application/RayInfo.cpp.o:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Application/RayInfo.cpp.o
.PHONY : src/Application/RayInfo.cpp.o

src/Application/RayInfo.i: src/Application/RayInfo.cpp.i
.PHONY : src/Application/RayInfo.i

# target to preprocess a source file
src/Application/RayInfo.cpp.i:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Application/RayInfo.cpp.i
.PHONY : src/Application/RayInfo.cpp.i

src/Application/RayInfo.s: src/Application/RayInfo.cpp.s
.PHONY : src/Application/RayInfo.s

# target to generate assembly for a file
src/Application/RayInfo.cpp.s:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Application/RayInfo.cpp.s
.PHONY : src/Application/RayInfo.cpp.s

src/Application/Renderer.o: src/Application/Renderer.cpp.o
.PHONY : src/Application/Renderer.o

# target to build an object file
src/Application/Renderer.cpp.o:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Application/Renderer.cpp.o
.PHONY : src/Application/Renderer.cpp.o

src/Application/Renderer.i: src/Application/Renderer.cpp.i
.PHONY : src/Application/Renderer.i

# target to preprocess a source file
src/Application/Renderer.cpp.i:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Application/Renderer.cpp.i
.PHONY : src/Application/Renderer.cpp.i

src/Application/Renderer.s: src/Application/Renderer.cpp.s
.PHONY : src/Application/Renderer.s

# target to generate assembly for a file
src/Application/Renderer.cpp.s:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Application/Renderer.cpp.s
.PHONY : src/Application/Renderer.cpp.s

src/Application/SceneInfo.o: src/Application/SceneInfo.cpp.o
.PHONY : src/Application/SceneInfo.o

# target to build an object file
src/Application/SceneInfo.cpp.o:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Application/SceneInfo.cpp.o
.PHONY : src/Application/SceneInfo.cpp.o

src/Application/SceneInfo.i: src/Application/SceneInfo.cpp.i
.PHONY : src/Application/SceneInfo.i

# target to preprocess a source file
src/Application/SceneInfo.cpp.i:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Application/SceneInfo.cpp.i
.PHONY : src/Application/SceneInfo.cpp.i

src/Application/SceneInfo.s: src/Application/SceneInfo.cpp.s
.PHONY : src/Application/SceneInfo.s

# target to generate assembly for a file
src/Application/SceneInfo.cpp.s:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Application/SceneInfo.cpp.s
.PHONY : src/Application/SceneInfo.cpp.s

src/Application/main.o: src/Application/main.cpp.o
.PHONY : src/Application/main.o

# target to build an object file
src/Application/main.cpp.o:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Application/main.cpp.o
.PHONY : src/Application/main.cpp.o

src/Application/main.i: src/Application/main.cpp.i
.PHONY : src/Application/main.i

# target to preprocess a source file
src/Application/main.cpp.i:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Application/main.cpp.i
.PHONY : src/Application/main.cpp.i

src/Application/main.s: src/Application/main.cpp.s
.PHONY : src/Application/main.s

# target to generate assembly for a file
src/Application/main.cpp.s:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Application/main.cpp.s
.PHONY : src/Application/main.cpp.s

src/Objects/Box.o: src/Objects/Box.cpp.o
.PHONY : src/Objects/Box.o

# target to build an object file
src/Objects/Box.cpp.o:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Objects/Box.cpp.o
.PHONY : src/Objects/Box.cpp.o

src/Objects/Box.i: src/Objects/Box.cpp.i
.PHONY : src/Objects/Box.i

# target to preprocess a source file
src/Objects/Box.cpp.i:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Objects/Box.cpp.i
.PHONY : src/Objects/Box.cpp.i

src/Objects/Box.s: src/Objects/Box.cpp.s
.PHONY : src/Objects/Box.s

# target to generate assembly for a file
src/Objects/Box.cpp.s:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Objects/Box.cpp.s
.PHONY : src/Objects/Box.cpp.s

src/Objects/Plane.o: src/Objects/Plane.cpp.o
.PHONY : src/Objects/Plane.o

# target to build an object file
src/Objects/Plane.cpp.o:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Objects/Plane.cpp.o
.PHONY : src/Objects/Plane.cpp.o

src/Objects/Plane.i: src/Objects/Plane.cpp.i
.PHONY : src/Objects/Plane.i

# target to preprocess a source file
src/Objects/Plane.cpp.i:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Objects/Plane.cpp.i
.PHONY : src/Objects/Plane.cpp.i

src/Objects/Plane.s: src/Objects/Plane.cpp.s
.PHONY : src/Objects/Plane.s

# target to generate assembly for a file
src/Objects/Plane.cpp.s:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Objects/Plane.cpp.s
.PHONY : src/Objects/Plane.cpp.s

src/Objects/Sphere.o: src/Objects/Sphere.cpp.o
.PHONY : src/Objects/Sphere.o

# target to build an object file
src/Objects/Sphere.cpp.o:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Objects/Sphere.cpp.o
.PHONY : src/Objects/Sphere.cpp.o

src/Objects/Sphere.i: src/Objects/Sphere.cpp.i
.PHONY : src/Objects/Sphere.i

# target to preprocess a source file
src/Objects/Sphere.cpp.i:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Objects/Sphere.cpp.i
.PHONY : src/Objects/Sphere.cpp.i

src/Objects/Sphere.s: src/Objects/Sphere.cpp.s
.PHONY : src/Objects/Sphere.s

# target to generate assembly for a file
src/Objects/Sphere.cpp.s:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Objects/Sphere.cpp.s
.PHONY : src/Objects/Sphere.cpp.s

src/Objects/Triangle.o: src/Objects/Triangle.cpp.o
.PHONY : src/Objects/Triangle.o

# target to build an object file
src/Objects/Triangle.cpp.o:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Objects/Triangle.cpp.o
.PHONY : src/Objects/Triangle.cpp.o

src/Objects/Triangle.i: src/Objects/Triangle.cpp.i
.PHONY : src/Objects/Triangle.i

# target to preprocess a source file
src/Objects/Triangle.cpp.i:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Objects/Triangle.cpp.i
.PHONY : src/Objects/Triangle.cpp.i

src/Objects/Triangle.s: src/Objects/Triangle.cpp.s
.PHONY : src/Objects/Triangle.s

# target to generate assembly for a file
src/Objects/Triangle.cpp.s:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Objects/Triangle.cpp.s
.PHONY : src/Objects/Triangle.cpp.s

src/RayTracer/Pixel.o: src/RayTracer/Pixel.cpp.o
.PHONY : src/RayTracer/Pixel.o

# target to build an object file
src/RayTracer/Pixel.cpp.o:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/RayTracer/Pixel.cpp.o
.PHONY : src/RayTracer/Pixel.cpp.o

src/RayTracer/Pixel.i: src/RayTracer/Pixel.cpp.i
.PHONY : src/RayTracer/Pixel.i

# target to preprocess a source file
src/RayTracer/Pixel.cpp.i:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/RayTracer/Pixel.cpp.i
.PHONY : src/RayTracer/Pixel.cpp.i

src/RayTracer/Pixel.s: src/RayTracer/Pixel.cpp.s
.PHONY : src/RayTracer/Pixel.s

# target to generate assembly for a file
src/RayTracer/Pixel.cpp.s:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/RayTracer/Pixel.cpp.s
.PHONY : src/RayTracer/Pixel.cpp.s

src/RayTracer/RayTracer.o: src/RayTracer/RayTracer.cpp.o
.PHONY : src/RayTracer/RayTracer.o

# target to build an object file
src/RayTracer/RayTracer.cpp.o:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/RayTracer/RayTracer.cpp.o
.PHONY : src/RayTracer/RayTracer.cpp.o

src/RayTracer/RayTracer.i: src/RayTracer/RayTracer.cpp.i
.PHONY : src/RayTracer/RayTracer.i

# target to preprocess a source file
src/RayTracer/RayTracer.cpp.i:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/RayTracer/RayTracer.cpp.i
.PHONY : src/RayTracer/RayTracer.cpp.i

src/RayTracer/RayTracer.s: src/RayTracer/RayTracer.cpp.s
.PHONY : src/RayTracer/RayTracer.s

# target to generate assembly for a file
src/RayTracer/RayTracer.cpp.s:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/RayTracer/RayTracer.cpp.s
.PHONY : src/RayTracer/RayTracer.cpp.s

src/RayTracer/Util.o: src/RayTracer/Util.cpp.o
.PHONY : src/RayTracer/Util.o

# target to build an object file
src/RayTracer/Util.cpp.o:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/RayTracer/Util.cpp.o
.PHONY : src/RayTracer/Util.cpp.o

src/RayTracer/Util.i: src/RayTracer/Util.cpp.i
.PHONY : src/RayTracer/Util.i

# target to preprocess a source file
src/RayTracer/Util.cpp.i:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/RayTracer/Util.cpp.i
.PHONY : src/RayTracer/Util.cpp.i

src/RayTracer/Util.s: src/RayTracer/Util.cpp.s
.PHONY : src/RayTracer/Util.s

# target to generate assembly for a file
src/RayTracer/Util.cpp.s:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/RayTracer/Util.cpp.s
.PHONY : src/RayTracer/Util.cpp.s

src/Scene/AABB.o: src/Scene/AABB.cpp.o
.PHONY : src/Scene/AABB.o

# target to build an object file
src/Scene/AABB.cpp.o:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Scene/AABB.cpp.o
.PHONY : src/Scene/AABB.cpp.o

src/Scene/AABB.i: src/Scene/AABB.cpp.i
.PHONY : src/Scene/AABB.i

# target to preprocess a source file
src/Scene/AABB.cpp.i:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Scene/AABB.cpp.i
.PHONY : src/Scene/AABB.cpp.i

src/Scene/AABB.s: src/Scene/AABB.cpp.s
.PHONY : src/Scene/AABB.s

# target to generate assembly for a file
src/Scene/AABB.cpp.s:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Scene/AABB.cpp.s
.PHONY : src/Scene/AABB.cpp.s

src/Scene/BoundingVolumeNode.o: src/Scene/BoundingVolumeNode.cpp.o
.PHONY : src/Scene/BoundingVolumeNode.o

# target to build an object file
src/Scene/BoundingVolumeNode.cpp.o:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Scene/BoundingVolumeNode.cpp.o
.PHONY : src/Scene/BoundingVolumeNode.cpp.o

src/Scene/BoundingVolumeNode.i: src/Scene/BoundingVolumeNode.cpp.i
.PHONY : src/Scene/BoundingVolumeNode.i

# target to preprocess a source file
src/Scene/BoundingVolumeNode.cpp.i:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Scene/BoundingVolumeNode.cpp.i
.PHONY : src/Scene/BoundingVolumeNode.cpp.i

src/Scene/BoundingVolumeNode.s: src/Scene/BoundingVolumeNode.cpp.s
.PHONY : src/Scene/BoundingVolumeNode.s

# target to generate assembly for a file
src/Scene/BoundingVolumeNode.cpp.s:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Scene/BoundingVolumeNode.cpp.s
.PHONY : src/Scene/BoundingVolumeNode.cpp.s

src/Scene/Camera.o: src/Scene/Camera.cpp.o
.PHONY : src/Scene/Camera.o

# target to build an object file
src/Scene/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Scene/Camera.cpp.o
.PHONY : src/Scene/Camera.cpp.o

src/Scene/Camera.i: src/Scene/Camera.cpp.i
.PHONY : src/Scene/Camera.i

# target to preprocess a source file
src/Scene/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Scene/Camera.cpp.i
.PHONY : src/Scene/Camera.cpp.i

src/Scene/Camera.s: src/Scene/Camera.cpp.s
.PHONY : src/Scene/Camera.s

# target to generate assembly for a file
src/Scene/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Scene/Camera.cpp.s
.PHONY : src/Scene/Camera.cpp.s

src/Scene/Object.o: src/Scene/Object.cpp.o
.PHONY : src/Scene/Object.o

# target to build an object file
src/Scene/Object.cpp.o:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Scene/Object.cpp.o
.PHONY : src/Scene/Object.cpp.o

src/Scene/Object.i: src/Scene/Object.cpp.i
.PHONY : src/Scene/Object.i

# target to preprocess a source file
src/Scene/Object.cpp.i:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Scene/Object.cpp.i
.PHONY : src/Scene/Object.cpp.i

src/Scene/Object.s: src/Scene/Object.cpp.s
.PHONY : src/Scene/Object.s

# target to generate assembly for a file
src/Scene/Object.cpp.s:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Scene/Object.cpp.s
.PHONY : src/Scene/Object.cpp.s

src/Scene/Scene.o: src/Scene/Scene.cpp.o
.PHONY : src/Scene/Scene.o

# target to build an object file
src/Scene/Scene.cpp.o:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Scene/Scene.cpp.o
.PHONY : src/Scene/Scene.cpp.o

src/Scene/Scene.i: src/Scene/Scene.cpp.i
.PHONY : src/Scene/Scene.i

# target to preprocess a source file
src/Scene/Scene.cpp.i:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Scene/Scene.cpp.i
.PHONY : src/Scene/Scene.cpp.i

src/Scene/Scene.s: src/Scene/Scene.cpp.s
.PHONY : src/Scene/Scene.s

# target to generate assembly for a file
src/Scene/Scene.cpp.s:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Scene/Scene.cpp.s
.PHONY : src/Scene/Scene.cpp.s

src/Shading/BlinnPhongBRDF.o: src/Shading/BlinnPhongBRDF.cpp.o
.PHONY : src/Shading/BlinnPhongBRDF.o

# target to build an object file
src/Shading/BlinnPhongBRDF.cpp.o:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Shading/BlinnPhongBRDF.cpp.o
.PHONY : src/Shading/BlinnPhongBRDF.cpp.o

src/Shading/BlinnPhongBRDF.i: src/Shading/BlinnPhongBRDF.cpp.i
.PHONY : src/Shading/BlinnPhongBRDF.i

# target to preprocess a source file
src/Shading/BlinnPhongBRDF.cpp.i:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Shading/BlinnPhongBRDF.cpp.i
.PHONY : src/Shading/BlinnPhongBRDF.cpp.i

src/Shading/BlinnPhongBRDF.s: src/Shading/BlinnPhongBRDF.cpp.s
.PHONY : src/Shading/BlinnPhongBRDF.s

# target to generate assembly for a file
src/Shading/BlinnPhongBRDF.cpp.s:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Shading/BlinnPhongBRDF.cpp.s
.PHONY : src/Shading/BlinnPhongBRDF.cpp.s

src/Shading/CookTorranceBRDF.o: src/Shading/CookTorranceBRDF.cpp.o
.PHONY : src/Shading/CookTorranceBRDF.o

# target to build an object file
src/Shading/CookTorranceBRDF.cpp.o:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Shading/CookTorranceBRDF.cpp.o
.PHONY : src/Shading/CookTorranceBRDF.cpp.o

src/Shading/CookTorranceBRDF.i: src/Shading/CookTorranceBRDF.cpp.i
.PHONY : src/Shading/CookTorranceBRDF.i

# target to preprocess a source file
src/Shading/CookTorranceBRDF.cpp.i:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Shading/CookTorranceBRDF.cpp.i
.PHONY : src/Shading/CookTorranceBRDF.cpp.i

src/Shading/CookTorranceBRDF.s: src/Shading/CookTorranceBRDF.cpp.s
.PHONY : src/Shading/CookTorranceBRDF.s

# target to generate assembly for a file
src/Shading/CookTorranceBRDF.cpp.s:
	$(MAKE) -f CMakeFiles/raytrace.dir/build.make CMakeFiles/raytrace.dir/src/Shading/CookTorranceBRDF.cpp.s
.PHONY : src/Shading/CookTorranceBRDF.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... parser"
	@echo "... raytrace"
	@echo "... rebuild_cache"
	@echo "... lib/parser/Parser.o"
	@echo "... lib/parser/Parser.i"
	@echo "... lib/parser/Parser.s"
	@echo "... lib/parser/TokenStream.o"
	@echo "... lib/parser/TokenStream.i"
	@echo "... lib/parser/TokenStream.s"
	@echo "... lib/parser/Tokenizer.o"
	@echo "... lib/parser/Tokenizer.i"
	@echo "... lib/parser/Tokenizer.s"
	@echo "... src/Application/Application.o"
	@echo "... src/Application/Application.i"
	@echo "... src/Application/Application.s"
	@echo "... src/Application/RayInfo.o"
	@echo "... src/Application/RayInfo.i"
	@echo "... src/Application/RayInfo.s"
	@echo "... src/Application/Renderer.o"
	@echo "... src/Application/Renderer.i"
	@echo "... src/Application/Renderer.s"
	@echo "... src/Application/SceneInfo.o"
	@echo "... src/Application/SceneInfo.i"
	@echo "... src/Application/SceneInfo.s"
	@echo "... src/Application/main.o"
	@echo "... src/Application/main.i"
	@echo "... src/Application/main.s"
	@echo "... src/Objects/Box.o"
	@echo "... src/Objects/Box.i"
	@echo "... src/Objects/Box.s"
	@echo "... src/Objects/Plane.o"
	@echo "... src/Objects/Plane.i"
	@echo "... src/Objects/Plane.s"
	@echo "... src/Objects/Sphere.o"
	@echo "... src/Objects/Sphere.i"
	@echo "... src/Objects/Sphere.s"
	@echo "... src/Objects/Triangle.o"
	@echo "... src/Objects/Triangle.i"
	@echo "... src/Objects/Triangle.s"
	@echo "... src/RayTracer/Pixel.o"
	@echo "... src/RayTracer/Pixel.i"
	@echo "... src/RayTracer/Pixel.s"
	@echo "... src/RayTracer/RayTracer.o"
	@echo "... src/RayTracer/RayTracer.i"
	@echo "... src/RayTracer/RayTracer.s"
	@echo "... src/RayTracer/Util.o"
	@echo "... src/RayTracer/Util.i"
	@echo "... src/RayTracer/Util.s"
	@echo "... src/Scene/AABB.o"
	@echo "... src/Scene/AABB.i"
	@echo "... src/Scene/AABB.s"
	@echo "... src/Scene/BoundingVolumeNode.o"
	@echo "... src/Scene/BoundingVolumeNode.i"
	@echo "... src/Scene/BoundingVolumeNode.s"
	@echo "... src/Scene/Camera.o"
	@echo "... src/Scene/Camera.i"
	@echo "... src/Scene/Camera.s"
	@echo "... src/Scene/Object.o"
	@echo "... src/Scene/Object.i"
	@echo "... src/Scene/Object.s"
	@echo "... src/Scene/Scene.o"
	@echo "... src/Scene/Scene.i"
	@echo "... src/Scene/Scene.s"
	@echo "... src/Shading/BlinnPhongBRDF.o"
	@echo "... src/Shading/BlinnPhongBRDF.i"
	@echo "... src/Shading/BlinnPhongBRDF.s"
	@echo "... src/Shading/CookTorranceBRDF.o"
	@echo "... src/Shading/CookTorranceBRDF.i"
	@echo "... src/Shading/CookTorranceBRDF.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

